sudo: required
services:
  - docker

before_install:
  - docker build -t atij/docker-react -f Dockerfile.dev .

script:
  - docker run atij/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-3"
  name: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-eu-west-3-655563260295"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"